# Installing Packages

In [1]:
# pip install ydata-profiling --user

# Importing Libraries

In [2]:
#Basic Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Dataset Profiling
from ydata_profiling import ProfileReport

#Sklearn libraries and modules
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# Import label encoder 
from sklearn import preprocessing 

#Object Initialization
sc = StandardScaler()
label_encoder = preprocessing.LabelEncoder() 

C:\Users\st7725\AppData\Roaming\Python\Python39\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\st7725\AppData\Roaming\Python\Python39\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


# Reading the Dataset

In [3]:
train_dataset = pd.read_csv('train.csv')
test_dataset = pd.read_csv('test.csv')

# EDA

In [4]:
# profile = ProfileReport(train_df)
# profile

# Version 1

In [5]:
#CReating Version Copies
train_df = train_dataset
test_df = test_dataset

#Dropping the rows with null values
train_df = train_df.dropna()

#Dropping Columns
train_df = train_df.drop(['PassengerId', 'Cabin','Name'], axis=1)
  
# Encode labels in column 'species'. 
train_df['HomePlanet']= label_encoder.fit_transform(train_df['HomePlanet'])  
train_df['CryoSleep']= label_encoder.fit_transform(train_df['CryoSleep'])  
train_df['Destination']= label_encoder.fit_transform(train_df['Destination'])  
train_df['VIP']= label_encoder.fit_transform(train_df['VIP'])  
train_df['Transported']= label_encoder.fit_transform(train_df['Transported'])  

X = train_df.iloc[:, :-1].values
y = train_df.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
#Logistic Regression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

#Predicted Values against test
y_pred = classifier.predict(X_test)

#Accuracy and confusion matrix
print("Logistic Regression")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#K-Nearest Neighbors
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("K-Nearest Neighbors")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Support Vector Machines
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Support Vector Machines")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Kernel SVM
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Kernel SVM")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Naive Bayes
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Naive Bayes")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Decision Tree
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Decision Tree")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Random Decision Tree
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Random Decision Tree")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

Logistic Regression
[[636 195]
 [168 653]]
Accuracy:  0.7802663438256658


K-Nearest Neighbors
[[629 202]
 [182 639]]
Accuracy:  0.7675544794188862




C:\Users\st7725\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


Support Vector Machines
[[643 188]
 [178 643]]
Accuracy:  0.7784503631961259


Kernel SVM
[[641 190]
 [169 652]]
Accuracy:  0.7826876513317191


Naive Bayes
[[386 445]
 [ 71 750]]
Accuracy:  0.6876513317191283


Decision Tree
[[582 249]
 [179 642]]
Accuracy:  0.7409200968523002


Random Decision Tree
[[652 179]
 [188 633]]
Accuracy:  0.7778450363196125




# On The Actual Test Dataset

In [7]:
# #Dropping Columns
# test_df = test_df.drop(['PassengerId', 'Cabin','Name'], axis=1)
  
# # Encode labels in column 'species'. 
# test_df['HomePlanet']= label_encoder.fit_transform(test_df['HomePlanet'])  
# test_df['CryoSleep']= label_encoder.fit_transform(test_df['CryoSleep'])  
# test_df['Destination']= label_encoder.fit_transform(test_df['Destination'])  
# test_df['VIP']= label_encoder.fit_transform(test_df['VIP'])  

# X_train = train_df.iloc[:, :-1].values
# y_train = train_df.iloc[:, -1].values

# X_test = test_df.iloc[:, :].values

# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

# Version 2

In [8]:
# #TESTING THE CRYOSLEEP DECISION TREE MODEL TO FILL IN MISSING VALUES 
# #CReating Version Copies
# train_df = train_dataset
# test_df = test_dataset

# #Dropping the rows with null values
# train_df = train_df.dropna()

# train_df['CryoSleep']= label_encoder.fit_transform(train_df['CryoSleep'])  

# #RoomService, FoodCourt, ShoppingMall, Spa, VRDeck
# train_df = train_df[['CryoSleep','RoomService',"FoodCourt", "ShoppingMall", "Spa", "VRDeck"]]

# X = train_df.iloc[:, 2:].values
# y = train_df.iloc[:, 0:1].values

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

# #Decision Tree
# classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
# classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_test)
# print("Decision Tree")
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# print("Accuracy: ",accuracy_score(y_test, y_pred))
# print('\n')

In [9]:
# #TESTING THE HomePlanet MODEL TO FILL IN MISSING VALUES 

# #RoomService, FoodCourt, ShoppingMall, Spa, VRDeck
# train_df = train_df[['HomePlanet',0,1]]

# X = train_df.iloc[:, 1:3].values
# y = train_df.iloc[:, 0:1].values

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# X_train = sc.fit_transform(X_train)
# X_test = sc.transform(X_test)

# #Decision Tree
# classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
# classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_test)
# print("Decision Tree")
# cm = confusion_matrix(y_test, y_pred)
# print(cm)
# print("Accuracy: ",accuracy_score(y_test, y_pred))
# print('\n')

In [10]:
# Calculating the correlation of column A against all others
# method{‘pearson’, ‘kendall’, ‘spearman’} 
# train_df.corr(method='kendall')['HomePlanet']

# # Encode labels in column 'species'. 
# train_df['Destination']= label_encoder.fit_transform(train_df['Destination'])  
# train_df['VIP']= label_encoder.fit_transform(train_df['VIP'])  
# train_df['Transported']= label_encoder.fit_transform(train_df['Transported'])  
# train_df['Cabin_1']= label_encoder.fit_transform(train_df['Cabin_1'])  
# train_df['Cabin_3']= label_encoder.fit_transform(train_df['Cabin_3'])  

# train_df = train_df.astype({'family':int, 'family_count':int,'HomePlanet': int, 'CryoSleep': int, 'Destination': int, 'VIP': int, 'Transported': int, 'Cabin_1': int, 'Cabin_3': int})

# profile = ProfileReport(train_df)
# profile

In [11]:
#CReating Version Copies
train_df = train_dataset

# Handling RoomService, FoodCourt, ShoppingMall, Spa, VRDeck
train_df['Total_Spent']= train_df[['RoomService',"FoodCourt", "ShoppingMall", "Spa", "VRDeck"]].sum(axis=1)

#Dropping these columns
train_df = train_df.drop(['RoomService',"FoodCourt", "ShoppingMall", "Spa", "VRDeck"], axis=1)

#Handling Cabin
#Splitting the column 'Cabin'
x = train_df["Cabin"].str.split("/", expand=True)
#Adding these new columns back to the original dataset
train_df = pd.concat([train_df.reset_index(drop=True),x.reset_index(drop=True)], axis=1)
#Dropping Cabin
train_df = train_df.drop(['Cabin'], axis=1)

#Handling CryoSleep
cryosleep_model = train_df[['PassengerId','CryoSleep','Total_Spent']]

#Showcasing the encoded labels for cryosleep
label_encoder.fit(cryosleep_model['CryoSleep'])
cryosleep_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print(cryosleep_mapping)

#Changing the dataset 
cryosleep_model['CryoSleep']= label_encoder.fit_transform(cryosleep_model['CryoSleep']) 

#CryoSleep test set
cs_test = cryosleep_model.loc[cryosleep_model['CryoSleep'] == 2]

#Cryosleep train set
cs_train = cryosleep_model.loc[cryosleep_model['CryoSleep'] != 2]

#Creating the predictor variables 
X_train = cs_train.iloc[:,2:].values
y_train = cs_train.iloc[:, 1:2].values

#Creating the predicted variables 
X_test = cs_test.iloc[:,2:].values

#Scaling dimnesions 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the decision tree
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

#Adding predictions back to the original 
cs_test['CryoSleep'] = y_pred

#Combining both results 
cryosleep_model = pd.concat([cs_train, cs_test], ignore_index=True) 

#Dropping the old column
train_df = train_df.drop('CryoSleep',axis=1)

#Getting the new cryosleep column
train_df = train_df.merge(cryosleep_model[['PassengerId','CryoSleep']], on='PassengerId', how='left')

#Handling HomePlanet
homeplanet_model = train_df[['PassengerId','HomePlanet',0,1]]

#Showcasing the encoded labels for homeplanet
label_encoder.fit(homeplanet_model['HomePlanet'])
homeplanet_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print(homeplanet_mapping)

#Changing the dataset 
homeplanet_model['HomePlanet']= label_encoder.fit_transform(homeplanet_model['HomePlanet']) 
homeplanet_model[0]= label_encoder.fit_transform(homeplanet_model[0]) 

#HomePlanet test set
hp_test = homeplanet_model.loc[homeplanet_model['HomePlanet'] == 3]

#HomePlanet train set
hp_train = homeplanet_model.loc[homeplanet_model['HomePlanet'] != 3]

#Special case 
hp_test_2 = hp_test.loc[homeplanet_model[1].isnull()]
hp_test_2["HomePlanet"] = 0
#train_df['HomePlanet'].mode()[0]

hp_train_2 = hp_train.loc[homeplanet_model[1].isnull()]

#Fixing the Training anf Testing sets
hp_test = hp_test.loc[homeplanet_model[1].notnull()]
hp_train = hp_train.loc[homeplanet_model[1].notnull()]

#Creating the predictor variables 
X_train = hp_train.iloc[:,2:].values
y_train = hp_train.iloc[:, 1:2].values


#Creating the predicted variables 
X_test = hp_test.iloc[:,2:].values

#Scaling dimnesions 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Training the decision tree
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

#Adding predictions back to the original 
hp_test['HomePlanet'] = y_pred

#Combining both results 
homeplanet_model = pd.concat([hp_train, hp_test, hp_train_2, hp_test_2], ignore_index=True) 

#Dropping the old column
train_df = train_df.drop('HomePlanet',axis=1)

#Getting the new cryosleep column
train_df = train_df.merge(homeplanet_model[['PassengerId','HomePlanet']], on='PassengerId', how='left')

#Handling PassengerId
#'PassengerId',
train_df = train_df.drop(['Name'], axis=1)

#Handling VIP
train_df["VIP"].fillna(False, inplace = True)

#Dropping the rows with null values
train_df = train_df.dropna()

#Dropping Any Duplicates
train_df = train_df.drop_duplicates()

#Renaming columns 
train_df.rename(columns = {0:'Cabin_1',1:'Cabin_2',2:'Cabin_3'}, inplace = True) 

#Handling PassengerId
#Splitting the column 'PassengerId'
x = train_df["PassengerId"].str.split("_", expand=True)
#Adding these new columns back to the original dataset
train_df = pd.concat([train_df.reset_index(drop=True),x.reset_index(drop=True)], axis=1)
#Dropping Cabin
train_df = train_df.drop(['PassengerId'], axis=1)
#Renaming columns 
train_df.rename(columns = {0:'Group_Id',1:'PID'}, inplace = True) 
train_df = train_df.astype({'PID': int})
train_df['family'] = train_df.groupby('Group_Id')['PID'].transform(lambda x: 1 if x.nunique() > 1 else 0)
train_df['family_count'] = train_df.groupby('Group_Id')['PID'].transform(lambda x: x.nunique())
train_df = train_df.drop(['Group_Id','PID'],axis=1)

#Moving Columns
train_df = train_df.reindex(sorted(train_df.columns), axis=1)
train_df = train_df[[c for c in train_df if c not in ['Transported']] + ['Transported']]


# Encode labels in column 'species'. 
train_df['Destination']= label_encoder.fit_transform(train_df['Destination'])  
train_df['VIP']= label_encoder.fit_transform(train_df['VIP'])  

label_encoder.fit(train_df['Transported'])
tp = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
print(tp)
train_df['Transported']= label_encoder.fit_transform(train_df['Transported'])
# train_df = train_df.replace({True: 1, False: 0})

train_df['Cabin_1']= label_encoder.fit_transform(train_df['Cabin_1'])  
train_df['Cabin_3']= label_encoder.fit_transform(train_df['Cabin_3'])  

train_df = train_df.drop(['Age','VIP','Total_Spent','Cabin_2','Cabin_3','family_count'], axis=1)
#remove family_count, Cabin_3, Total_Spent, VIP, Age
# keep family, HomePlanet, CryoSleep, Cabin_2, Cabin_1, Destination

X = train_df.iloc[:, :-1].values
y = train_df.iloc[:, -1].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Logistic Regression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

#Predicted Values against test
y_pred = classifier.predict(X_test)

#Accuracy and confusion matrix
print("Logistic Regression")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#K-Nearest Neighbors
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("K-Nearest Neighbors")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Support Vector Machines
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Support Vector Machines")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Kernel SVM
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Kernel SVM")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Naive Bayes
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Naive Bayes")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Decision Tree
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Decision Tree")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

#Random Decision Tree
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
print("Random Decision Tree")
cm = confusion_matrix(y_test, y_pred)
print(cm)
print("Accuracy: ",accuracy_score(y_test, y_pred))
print('\n')

{False: 0, True: 1, nan: 2}
{'Earth': 0, 'Europa': 1, 'Mars': 2, nan: 3}


C:\Users\st7725\AppData\Local\Temp\ipykernel_21144\3509536503.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cryosleep_model['CryoSleep']= label_encoder.fit_transform(cryosleep_model['CryoSleep'])
C:\Users\st7725\AppData\Local\Temp\ipykernel_21144\3509536503.py:52: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cs_test['CryoSleep'] = y_pred
C:\Users\st7725\AppData\Local\Temp\ipykernel_21144\3509536503.py:72: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try

{False: 0, True: 1}
Logistic Regression
[[827 189]
 [398 622]]
Accuracy:  0.7116895874263262




C:\Users\st7725\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


K-Nearest Neighbors
[[761 255]
 [426 594]]
Accuracy:  0.6655206286836935


Support Vector Machines
[[857 159]
 [417 603]]
Accuracy:  0.7170923379174853


Kernel SVM
[[857 159]
 [417 603]]
Accuracy:  0.7170923379174853


Naive Bayes
[[749 267]
 [358 662]]
Accuracy:  0.6930255402750491


Decision Tree
[[828 188]
 [382 638]]
Accuracy:  0.7200392927308448


Random Decision Tree
[[786 230]
 [361 659]]
Accuracy:  0.7097249508840865




In [12]:
test_df = test_dataset

#Handling Cabin
x = test_df["Cabin"].str.split("/", expand=True)
test_df = pd.concat([test_df.reset_index(drop=True),x.reset_index(drop=True)], axis=1)
test_df = test_df.drop(['Cabin'], axis=1)

#Handling HomePlanet
homeplanet_model = test_df[['PassengerId','HomePlanet',0,1]]
label_encoder.fit(homeplanet_model['HomePlanet'])
homeplanet_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
homeplanet_model['HomePlanet']= label_encoder.fit_transform(homeplanet_model['HomePlanet']) 
homeplanet_model[0]= label_encoder.fit_transform(homeplanet_model[0]) 
hp_test = homeplanet_model.loc[homeplanet_model['HomePlanet'] == 3]
hp_train = homeplanet_model.loc[homeplanet_model['HomePlanet'] != 3]
hp_test_2 = hp_test.loc[homeplanet_model[1].isnull()]
hp_test_2["HomePlanet"] = 0
hp_train_2 = hp_train.loc[homeplanet_model[1].isnull()]
hp_test = hp_test.loc[homeplanet_model[1].notnull()]
hp_train = hp_train.loc[homeplanet_model[1].notnull()]
X_train = hp_train.iloc[:,2:].values
y_train = hp_train.iloc[:, 1:2].values
X_test = hp_test.iloc[:,2:].values
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
hp_test['HomePlanet'] = y_pred
homeplanet_model = pd.concat([hp_train, hp_test, hp_train_2, hp_test_2], ignore_index=True) 
test_df = test_df.drop('HomePlanet',axis=1)
test_df = test_df.merge(homeplanet_model[['PassengerId','HomePlanet']], on='PassengerId', how='left')

#Renaming columns 
test_df.rename(columns = {0:'Cabin_1',1:'Cabin_2',2:'Cabin_3'}, inplace = True) 

# Handling RoomService, FoodCourt, ShoppingMall, Spa, VRDeck
test_df['Total_Spent']= test_df[['RoomService',"FoodCourt", "ShoppingMall", "Spa", "VRDeck"]].sum(axis=1)
test_df = test_df.drop(['RoomService',"FoodCourt", "ShoppingMall", "Spa", "VRDeck"], axis=1)

#Handling CryoSleep
cryosleep_model = test_df[['PassengerId','CryoSleep','Total_Spent']]
label_encoder.fit(cryosleep_model['CryoSleep'])
cryosleep_mapping = dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_)))
cryosleep_model['CryoSleep']= label_encoder.fit_transform(cryosleep_model['CryoSleep']) 
cs_test = cryosleep_model.loc[cryosleep_model['CryoSleep'] == 2]
cs_train = cryosleep_model.loc[cryosleep_model['CryoSleep'] != 2]
X_train = cs_train.iloc[:,2:].values
y_train = cs_train.iloc[:, 1:2].values
X_test = cs_test.iloc[:,2:].values
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cs_test['CryoSleep'] = y_pred
cryosleep_model = pd.concat([cs_train, cs_test], ignore_index=True) 
test_df = test_df.drop('CryoSleep',axis=1)
test_df = test_df.merge(cryosleep_model[['PassengerId','CryoSleep']], on='PassengerId', how='left')

#Handling PassengerID
x = test_df["PassengerId"].str.split("_", expand=True)
test_df = pd.concat([test_df.reset_index(drop=True),x.reset_index(drop=True)], axis=1)
test_df = test_df.drop(['PassengerId'], axis=1)
test_df.rename(columns = {0:'Group_Id',1:'PID'}, inplace = True) 
test_df = test_df.astype({'PID': int})
test_df['family'] = test_df.groupby('Group_Id')['PID'].transform(lambda x: 1 if x.nunique() > 1 else 0)
test_df['family_count'] = test_df.groupby('Group_Id')['PID'].transform(lambda x: x.nunique())
test_df = test_df.drop(['Group_Id','PID'],axis=1)

#Dropping Name Column
test_df = test_df.drop(['Name'],axis=1)

#Ordering Columns
test_df = test_df.reindex(sorted(test_df.columns), axis=1)

C:\Users\st7725\AppData\Local\Temp\ipykernel_21144\3909631341.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homeplanet_model['HomePlanet']= label_encoder.fit_transform(homeplanet_model['HomePlanet'])
C:\Users\st7725\AppData\Local\Temp\ipykernel_21144\3909631341.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  homeplanet_model[0]= label_encoder.fit_transform(homeplanet_model[0])
C:\Users\st7725\AppData\Local\Temp\ipykernel_21144\3909631341.py:17: SettingWithCopyWarning: 
A value is trying to be se

In [13]:
# Encode labels in column 'species'. 
test_df['Destination']= label_encoder.fit_transform(test_df['Destination'])  
test_df['VIP']= label_encoder.fit_transform(test_df['VIP'])   
test_df['Cabin_1']= label_encoder.fit_transform(test_df['Cabin_1'])  
test_df['Cabin_3']= label_encoder.fit_transform(test_df['Cabin_3'])  

test_df = test_df.drop(['Age','VIP','Total_Spent','Cabin_2','Cabin_3','family_count'], axis=1)

X_train = train_df.iloc[:, :-1].values
y_train = train_df.iloc[:, -1].values

X_test = test_df.iloc[:,:].values

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Random Decision Tree
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [14]:
submission = test_dataset
submission['Transported'] = y_pred
submission = submission[['PassengerId','Transported']]
submission = submission.replace({1: True, 0: False})

C:\Users\st7725\AppData\Local\Temp\ipykernel_21144\1448603096.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  submission = submission.replace({1: True, 0: False})


In [15]:
submission.to_csv('final_prediction.csv',index = False)